### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by tanmaya-panda1**
#### Pull Request Description

_[Add a description of your pull request here]_

---

#### Future Release Comment

_[Add description of your change, to include in the next release]_
_[Delete any or all irrelevant sections, e.g. if your change does not warrant a release comment at all]_

**Breaking Changes:**

- None

**Features:**

- None

**Fixes:**

- None

### CODE REVIEW

**Comment by ohadbitt** [comment]
Just a question - how did you test this?
Also - maybe we should start linting our files with intellij ctrl+alt+L

**Comment by ag-ramachandran** [comment]
@tanmaya-panda1 can you reply to the comments above

**Comment by ag-ramachandran** [comment]
@tanmaya-panda1 , @ohadbitt  working on tests. Will push the code in 1 hour or so

**Comment by ohadbitt** [comment]
> files

I think manual test is better but it might be cumbersome ..

**Comment by tanmaya-panda1** [comment]
> Just a question - how did you test this? Also - maybe we should start linting our files with intellij ctrl+alt+L

Hi Ohad, I tested it by configuring the system level proxy for all outbound connections. The proxy I used was free proxy from internet. I am yet to test for https connections. I will update here once done.

**Comment by ag-ramachandran** [comment]
@tanmaya-panda1 @ohadbitt 
In the E2E test for the Avro ingest scenario, I sent it through an embedded proxy. There is some code that needed changing that I have done. 
Pl. provide feedback. We can manually test through a proxy tomorrow as well.

image

**Review by ohadbitt — APPROVED** [review]

**Review by ag-ramachandran — APPROVED** [review]

**Pull request merged**
